version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sme_pg
    environment:
      POSTGRES_USER: sme
      POSTGRES_PASSWORD: sme
      POSTGRES_DB: sme_finance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
